wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1650557956
    t:
      1:
      - 1
      - 55
      3:
      - 24
      4: 3.9.7
      5: 0.12.12
      8:
      - 3
      - 5
